source 'https://rubygems.org'

gemspec

if RUBY_VERSION >= '3.0.0'
  gem 'webrick', '>= 1.7.0' # No longer bundled by default since Ruby 3.0
end

# This file was generated by Appraisal

# gem 'lograge'
# gem 'makara'
# gem 'mysql2'
# gem 'pg', '< 1.0', platform: :ruby
# gem 'rails', '~> 5.2.1'
# gem 'redis'
# gem 'redis-rails'
# gem 'sprockets', '< 4'
# gem 'sqlite3'
